# https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 4
  timeout: 1m
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: github-actions

linters:
  enable:
    - golint
    - gosec
    - lll
    - wsl

linters-settings:
  gosec:
    excludes:
      - G107
