# https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 4
  timeout: 1m
  modules-download-mode: readonly
  allow-parallel-runners: true

outputs:
  format: colored-line-number

linters:
  enable:
    - revive
    - gosec
    - lll
    - wsl

linters-settings:
  gosec:
    excludes:
      - G107
