---
AWSTemplateFormatVersion: 2010-09-09
Description: rito-news-feeds - CloudFormation stack for CDN deployment

Parameters:
  BucketName:
    Type: String
    Description: A S3 bucket name, eg. my-bucket-name

  DomainName:
    Type: String
    Description: A domain name, eg. example.com.

  Stage:
    Type: String
    Default: dev
    Description: Stage name aka dev/prod

Resources:
  s3WebSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${Stage}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - '*'
      Tags:
        - Key: Product
          Value: rito-news
        - Key: Name
          Value: !Ref BucketName
        - Key: Stage
          Value: !Ref Stage

  s3WebSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3WebSiteBucket
      PolicyDocument:
        Id: !Sub '${s3WebSiteBucket}BucketPolicy'
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${cfOriginIdentity}'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${s3WebSiteBucket}/*'

  acmWebSiteCertificateSSL:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      Tags:
        - Key: Product
          Value: rito-news
        - Key: Name
          Value: !Ref DomainName
        - Key: Stage
          Value: !Ref Stage

  cfOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront Origin access identity for ${DomainName}'

  cfCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: RitoNewsFeedsCachePolicy
        MinTTL: 1
        DefaultTTL: 600
        MaxTTL: 900
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  cfDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref cfCachePolicy
          CachedMethods:
            - GET
            - HEAD
          Compress: True
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
          ResponseHeadersPolicyId: 60669652-455b-4ae9-85a4-c4c02393f86c # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html
          TargetOriginId: !Sub 'S3-origin-${s3WebSiteBucket}'
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: True
        Origins:
          - DomainName: !GetAtt s3WebSiteBucket.RegionalDomainName
            Id: !Sub 'S3-origin-${s3WebSiteBucket}'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${cfOriginIdentity}'
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref acmWebSiteCertificateSSL
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: Product
          Value: rito-news
        - Key: Name
          Value: !Ref DomainName
        - Key: Stage
          Value: !Ref Stage
