AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rito-news-feeds
  
  Generates an Atom, RSS and JSON feed based on github.com/Antosik/rito-news data

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 512
    Timeout: 300
    Tracing: Active
    Environment:
      Variables:
        BUCKET_NAME: !Ref BucketName
        DOMAIN_NAME: !Ref DomainName
        DISTRIBUTION_ID: !Ref DistributionId
        TTL: !Ref TTL

Parameters:
  BucketName:
    Type: String
    Description: A S3 bucket name, eg. my-bucket-name
  DomainName:
    Type: String
    Description: A domain name, eg. example.com.
  DistributionId:
    Type: String
    Description: CloudFormation distribution id
  Stage:
    Type: String
    Default: dev
    Description: Stage name aka dev/prod
  TTL:
    Type: Number
    Default: 15
    Description: Time-to-live for RSS feeds

Resources:
  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: chromium-layer
      ContentUri: ../layers/chromium
      CompatibleRuntimes:
        - go1.x
  LeagueOfLegendsStatusChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      Architectures:
        - arm64
      FunctionName: !Sub
        - 'rito-news-lol-status-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: bootstrap
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/lol/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  LeagueOfLegendsNewsChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      Architectures:
        - arm64
      FunctionName: !Sub
        - 'rito-news-lol-news-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: bootstrap
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/lol/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  LeagueOfLegendsEsportsChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: go1.x
      Architectures:
        - x86_64
      FunctionName: !Sub
        - 'rito-news-lol-esports-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: lolesports
      Timeout: 120
      Layers:
        - !Ref ChromiumLayer
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/lol/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  
  VALORANTStatusChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      Architectures:
        - arm64
      FunctionName: !Sub
        - 'rito-news-val-status-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: bootstrap
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/val/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  VALORANTNewsChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      Architectures:
        - arm64
      FunctionName: !Sub
        - 'rito-news-val-news-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: bootstrap
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/val/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  VALORANTEsportsChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: go1.x
      Architectures:
        - x86_64
      FunctionName: !Sub
        - 'rito-news-val-esports-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: valesports
      Timeout: 120
      Layers:
        - !Ref ChromiumLayer
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/val/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
            
  LegendsOfRuneterraStatusChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      Architectures:
        - arm64
      FunctionName: !Sub
        - 'rito-news-lor-status-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: bootstrap
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/lor/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
  LegendsOfRuneterraNewsChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: go1.x
      Architectures:
        - x86_64
      FunctionName: !Sub
        - 'rito-news-lor-news-${Stage}'
        - Stage: !Ref Stage
      CodeUri: ../
      Handler: lornews
      Timeout: 120
      Layers:
        - !Ref ChromiumLayer
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub
              - 'rate(${TTL} minutes)'
              - TTL: !Ref TTL
      Policies:
      - Statement:
        - Sid: S3WriteAccess
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub
            - "arn:aws:s3:::${BucketName}/lor/*"
            - BucketName: !Ref BucketName
        - Sid: CloudFrontInvalidationCreationAccess
          Effect: Allow
          Action:
          - cloudfront:CreateInvalidation
          Resource: !Sub
            - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
            - DistributionId: !Ref DistributionId
